# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
	- cd googletest
	- mkdir build
	- cd build
	- cmake ..
	- make
	- cd ..
	- mkdir build
	- cd build
	- cmake .. && make
